# @package _group_
version: 1
formatters:
  simple:
    format: '[%(levelname)-8s] %(message)s'
  datetime:
    format: '%(asctime)-15s %(levelname)-8s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
    level: DEBUG
  file:
    class: logging.FileHandler
    formatter: datetime
    filename: '/Temp/stock-ml/qstrader/qstrader_conf.log'
    level: INFO
root:
  handlers: [console, file]

disable_existing_loggers: false